import type { Headhunter, Review, SearchFirm, Ratings } from "./types";

// ===== 서치펌 Mock =====
export const MOCK_FIRMS: SearchFirm[] = [
  { id: "1", name: "로버트월터스 코리아", website: "https://robertwalters.co.kr", description: "글로벌 인재 채용 전문, 다국적 기업 포지션에 강점", specialty_fields: ["IT/개발", "금융", "마케팅"], email_domain: "robertwalters.com", status: "active", created_at: "2020-01-01" },
  { id: "2", name: "마이클페이지 코리아", website: "https://michaelpage.co.kr", description: "중간~시니어급 전문직 채용 특화, 외국계 기업 파트너십 강점", specialty_fields: ["금융", "핀테크", "IT/개발"], email_domain: "michaelpage.com", status: "active", created_at: "2020-02-01" },
  { id: "3", name: "헤이즈 코리아", website: "https://hays.co.kr", description: "IT, 엔지니어링, 건설 분야 전문 서치펌", specialty_fields: ["IT/개발", "엔지니어링", "인프라"], email_domain: "hays.co.kr", status: "active", created_at: "2020-03-01" },
  { id: "4", name: "맨파워그룹 코리아", website: "https://manpowergroup.co.kr", description: "글로벌 인력 솔루션 기업, 제조·IT 분야 강점", specialty_fields: ["제조", "IT/개발", "물류"], email_domain: "manpowergroup.co.kr", status: "active", created_at: "2020-04-01" },
  { id: "5", name: "커리어케어", website: "https://careercare.co.kr", description: "국내 대표 서치펌, 제조·IT 분야 폭넓은 네트워크", specialty_fields: ["IT/개발", "제조", "엔지니어링"], email_domain: "careercare.co.kr", status: "active", created_at: "2020-05-01" },
  { id: "6", name: "엘리트 서치", website: "https://elitesearch.co.kr", description: "IT/데이터/AI 전문 서치펌, 스타트업~대기업 커버", specialty_fields: ["IT/개발", "데이터", "AI"], email_domain: "elitesearch.co.kr", status: "active", created_at: "2020-06-01" },
  { id: "7", name: "HRK", website: "https://hrk.co.kr", description: "종합 헤드헌팅, IT·제조·바이오 분야 강점", specialty_fields: ["IT/개발", "제조", "바이오"], email_domain: "hrk.co.kr", status: "active", created_at: "2020-07-01" },
  { id: "8", name: "유니코써치", website: "https://unicosearch.com", description: "임원급 서치 전문, 그룹사 및 대기업 채용 파트너", specialty_fields: ["임원", "IT/개발", "경영/전략"], email_domain: "unicosearch.com", status: "active", created_at: "2020-08-01" },
  { id: "9", name: "콘페리", website: "https://kornferry.com", description: "글로벌 경영 컨설팅 겸 이그제큐티브 서치", specialty_fields: ["경영/전략", "임원", "컨설팅"], email_domain: "kornferry.com", status: "active", created_at: "2020-09-01" },
  { id: "10", name: "랜스타드 코리아", website: "https://randstad.co.kr", description: "세계 최대 인재 서비스 기업, IT·제조 분야 강점", specialty_fields: ["IT/개발", "제조", "물류"], email_domain: "randstad.co.kr", status: "active", created_at: "2020-10-01" },
];

// ===== 헤드헌터 Mock =====
export const MOCK_HEADHUNTERS: Headhunter[] = [
  {
    id: "1",
    name: "김서현",
    search_firm_id: "6",
    firm_name: "엘리트 서치",
    specialty_fields: ["IT/개발", "데이터", "AI"],
    total_rating: 4.8,
    review_count: 47,
    verified_review_count: 32,
    trust_badge_level: "full",
    linkedin_url: null,
    profile_image: null,
    phone: null,
    email: null,
    claimed_by: null,
    is_claimed: true,
    verification_level: "claimed",
    created_at: "2024-01-15",
  },
  {
    id: "2",
    name: "박준영",
    search_firm_id: "4",
    firm_name: "맨파워그룹 코리아",
    specialty_fields: ["금융", "컨설팅"],
    total_rating: 4.5,
    review_count: 38,
    verified_review_count: 21,
    trust_badge_level: "full",
    linkedin_url: null,
    profile_image: null,
    phone: null,
    email: null,
    claimed_by: null,
    is_claimed: true,
    verification_level: "claimed",
    created_at: "2024-02-20",
  },
  {
    id: "3",
    name: "이민지",
    search_firm_id: "1",
    firm_name: "로버트월터스 코리아",
    specialty_fields: ["마케팅", "세일즈", "커머스"],
    total_rating: 4.6,
    review_count: 29,
    verified_review_count: 18,
    trust_badge_level: "partial",
    linkedin_url: null,
    profile_image: null,
    phone: null,
    email: null,
    claimed_by: null,
    is_claimed: false,
    verification_level: "none",
    created_at: "2024-03-10",
  },
  {
    id: "4",
    name: "정우진",
    search_firm_id: "3",
    firm_name: "헤이즈 코리아",
    specialty_fields: ["IT/개발", "인프라"],
    total_rating: 4.3,
    review_count: 22,
    verified_review_count: 14,
    trust_badge_level: "partial",
    linkedin_url: null,
    profile_image: null,
    phone: null,
    email: null,
    claimed_by: null,
    is_claimed: false,
    verification_level: "none",
    created_at: "2024-04-05",
  },
  {
    id: "5",
    name: "최하은",
    search_firm_id: "5",
    firm_name: "커리어케어",
    specialty_fields: ["제조", "엔지니어링"],
    total_rating: 4.7,
    review_count: 35,
    verified_review_count: 25,
    trust_badge_level: "full",
    linkedin_url: null,
    profile_image: null,
    phone: null,
    email: null,
    claimed_by: null,
    is_claimed: true,
    verification_level: "claimed",
    created_at: "2024-05-12",
  },
  {
    id: "6",
    name: "한동현",
    search_firm_id: "2",
    firm_name: "마이클페이지 코리아",
    specialty_fields: ["금융", "핀테크"],
    total_rating: 4.4,
    review_count: 19,
    verified_review_count: 11,
    trust_badge_level: "partial",
    linkedin_url: null,
    profile_image: null,
    phone: null,
    email: null,
    claimed_by: null,
    is_claimed: false,
    verification_level: "none",
    created_at: "2024-06-01",
  },
];

export const MOCK_REVIEWS: (Review & { headhunter_name: string; headhunter_firm: string })[] = [
  {
    id: "r1",
    headhunter_id: "1",
    headhunter_name: "김서현",
    headhunter_firm: "엘리트 서치",
    reviewer_id: "u1",
    reviewer_type: "job_seeker",
    review_type: "verified",
    contact_date: "2024-08-15",
    job_field: "백엔드 개발",
    contact_channel: "linkedin",
    ratings: {
      professionalism: 5,
      communication: 5,
      reliability: 4,
      support: 5,
      transparency: 4,
    },
    keywords_positive: ["전문적", "빠른 응답", "맞춤 추천", "피드백 제공"],
    keywords_negative: [],
    content: "IT 업계에 대한 깊은 이해를 바탕으로 제 경력에 딱 맞는 포지션을 추천해주셨습니다. 면접 준비부터 연봉 협상까지 꼼꼼하게 코칭해주셔서 원하는 곳에 이직할 수 있었습니다.",
    nps_score: 10,
    headhunter_reply: null,
    created_at: "2024-09-01",
  },
  {
    id: "r2",
    headhunter_id: "3",
    headhunter_name: "이민지",
    headhunter_firm: "로버트월터스",
    reviewer_id: "u2",
    reviewer_type: "hr_manager",
    review_type: "verified",
    contact_date: "2024-07-20",
    job_field: "디지털 마케팅",
    contact_channel: "email",
    ratings: {
      professionalism: 5,
      communication: 4,
      reliability: 5,
      support: 4,
      transparency: 5,
    },
    keywords_positive: ["꼼꼼함", "시장 분석력", "솔직함"],
    keywords_negative: [],
    content: "채용 담당자 입장에서 정말 신뢰할 수 있는 헤드헌터입니다. 후보자 스크리닝이 정확하고, 시장 트렌드에 대한 인사이트도 공유해주셔서 채용 전략 수립에 큰 도움이 되었습니다.",
    nps_score: 9,
    headhunter_reply: null,
    created_at: "2024-08-25",
  },
  {
    id: "r3",
    headhunter_id: "5",
    headhunter_name: "최하은",
    headhunter_firm: "커리어케어",
    reviewer_id: "u3",
    reviewer_type: "job_seeker",
    review_type: "general",
    contact_date: "2024-09-10",
    job_field: "생산관리",
    contact_channel: "phone",
    ratings: {
      professionalism: 4,
      communication: 5,
      reliability: 5,
      support: 4,
      transparency: 4,
    },
    keywords_positive: ["친절함", "적극적", "빠른 응답"],
    keywords_negative: [],
    content: "제조업 분야 전문성이 뛰어나고, 처음 이직하는 저에게 전체 프로세스를 상세히 안내해주셨습니다. 연락도 적절한 빈도로 해주셔서 부담 없이 진행할 수 있었습니다.",
    nps_score: 9,
    headhunter_reply: null,
    created_at: "2024-09-20",
  },
  {
    id: "r4",
    headhunter_id: "1",
    headhunter_name: "김서현",
    headhunter_firm: "엘리트 서치",
    reviewer_id: "u4",
    reviewer_type: "hr_manager",
    review_type: "verified",
    contact_date: "2024-06-10",
    job_field: "프론트엔드 개발",
    contact_channel: "email",
    ratings: { professionalism: 5, communication: 4, reliability: 5, support: 5, transparency: 4 },
    keywords_positive: ["맞춤 추천", "빠른 응답", "업계 이해도 높음"],
    keywords_negative: [],
    content: "프론트엔드 시니어 채용에 김서현 컨설턴트를 통해 우수 후보자를 확보했습니다. 후보자 프리스크리닝이 정확해서 면접 효율이 매우 높았습니다. 채용 시장 트렌드 공유도 감사했습니다.",
    nps_score: 9,
    headhunter_reply: "좋은 평가 감사합니다. 앞으로도 좋은 후보자 매칭을 위해 최선을 다하겠습니다.",
    created_at: "2024-07-15",
  },
  {
    id: "r5",
    headhunter_id: "1",
    headhunter_name: "김서현",
    headhunter_firm: "엘리트 서치",
    reviewer_id: "u5",
    reviewer_type: "job_seeker",
    review_type: "general",
    contact_date: "2024-10-01",
    job_field: "데이터 엔지니어링",
    contact_channel: "linkedin",
    ratings: { professionalism: 4, communication: 5, reliability: 4, support: 4, transparency: 5 },
    keywords_positive: ["친절함", "투명함", "지속적 관리"],
    keywords_negative: ["포지션 미스매치"],
    content: "전반적으로 좋은 경험이었습니다. 다만 처음 제안받은 포지션이 제 경력과 다소 맞지 않아 조정이 필요했습니다. 이후 적합한 포지션을 다시 찾아주셔서 결과적으로 만족합니다.",
    nps_score: 7,
    headhunter_reply: null,
    created_at: "2024-10-20",
  },
  {
    id: "r6",
    headhunter_id: "2",
    headhunter_name: "박준영",
    headhunter_firm: "맨파워그룹 코리아",
    reviewer_id: "u6",
    reviewer_type: "job_seeker",
    review_type: "verified",
    contact_date: "2024-05-15",
    job_field: "리스크 관리",
    contact_channel: "phone",
    ratings: { professionalism: 5, communication: 4, reliability: 4, support: 5, transparency: 4 },
    keywords_positive: ["전문적", "협상 능력", "면접 코칭 우수"],
    keywords_negative: [],
    content: "금융권 이직에 큰 도움을 주셨습니다. 면접 전 회사별 면접 특성과 예상 질문을 알려주셔서 자신감 있게 준비할 수 있었습니다. 연봉 협상도 적극적으로 지원해주셨습니다.",
    nps_score: 9,
    headhunter_reply: "좋은 결과 있으시길 바랍니다. 감사합니다.",
    created_at: "2024-06-20",
  },
  {
    id: "r7",
    headhunter_id: "4",
    headhunter_name: "정우진",
    headhunter_firm: "헤이즈 코리아",
    reviewer_id: "u7",
    reviewer_type: "job_seeker",
    review_type: "general",
    contact_date: "2024-08-01",
    job_field: "DevOps",
    contact_channel: "linkedin",
    ratings: { professionalism: 4, communication: 3, reliability: 4, support: 4, transparency: 5 },
    keywords_positive: ["투명함", "적극적"],
    keywords_negative: ["연락 두절"],
    content: "초반에 적극적으로 포지션을 제안해주셨으나, 중간에 연락이 뜸해져서 다소 불안했습니다. 최종 결과는 좋았지만 중간 과정에서의 소통이 아쉬웠습니다.",
    nps_score: 6,
    headhunter_reply: null,
    created_at: "2024-09-05",
  },
  {
    id: "r8",
    headhunter_id: "6",
    headhunter_name: "한동현",
    headhunter_firm: "마이클페이지 코리아",
    reviewer_id: "u8",
    reviewer_type: "hr_manager",
    review_type: "verified",
    contact_date: "2024-07-01",
    job_field: "퀀트 트레이딩",
    contact_channel: "email",
    ratings: { professionalism: 4, communication: 5, reliability: 4, support: 4, transparency: 4 },
    keywords_positive: ["시장 분석력", "빠른 응답", "꼼꼼함"],
    keywords_negative: [],
    content: "핀테크 분야 채용을 진행하면서 시장 상황과 경쟁사 채용 동향 등 유용한 인사이트를 많이 제공해주셨습니다. 후보자 추천 속도도 빨랐습니다.",
    nps_score: 8,
    headhunter_reply: null,
    created_at: "2024-08-10",
  },
];

// ===== 유틸: 헤드헌터 평균 ratings 계산 =====
export function getHeadhunterAvgRatings(headhunterId: string): Ratings {
  const reviews = MOCK_REVIEWS.filter((r) => r.headhunter_id === headhunterId);
  if (reviews.length === 0) return { professionalism: 0, communication: 0, reliability: 0, support: 0, transparency: 0 };
  const sum: Ratings = { professionalism: 0, communication: 0, reliability: 0, support: 0, transparency: 0 };
  for (const r of reviews) {
    (Object.keys(sum) as (keyof Ratings)[]).forEach((k) => { sum[k] += r.ratings[k]; });
  }
  (Object.keys(sum) as (keyof Ratings)[]).forEach((k) => { sum[k] = parseFloat((sum[k] / reviews.length).toFixed(1)); });
  return sum;
}

// ===== 유틸: 서치펌별 헤드헌터 수, 평균 평점 =====
export function getFirmStats(firmId: string) {
  const hunters = MOCK_HEADHUNTERS.filter((h) => h.search_firm_id === firmId);
  const count = hunters.length;
  const avgRating = count > 0 ? parseFloat((hunters.reduce((s, h) => s + h.total_rating, 0) / count).toFixed(1)) : 0;
  const totalReviews = hunters.reduce((s, h) => s + h.review_count, 0);
  return { count, avgRating, totalReviews };
}
