-- users 테이블에 연속 로그인 추적 컬럼 추가
ALTER TABLE users
ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS login_streak INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_login_days INTEGER DEFAULT 0;
